CUDACXX=nvcc
CUDACXXFLAGS=-arch=sm_70 -O3
CXXFLAGS=-march=native -fopenmp
NSYS=nsys profile
NSYSFLAGS=--stats=true --force-overwrite=true


djk: dijkstra parellel.cu
	$(CUDACXX) $(CUDACXXFLAGS) -Xcompiler="$(CXXFLAGS)" streams.cu -o streams

fw: streams_solution.cu
	$(CUDACXX) $(CUDACXXFLAGS) -Xcompiler="$(CXXFLAGS)" streams_solution.cu -o streams_solution

profile: streams
	$(NSYS) $(NSYSFLAGS) -o streams-report ./streams

profile_solution: streams_solution
	$(NSYS) $(NSYSFLAGS) -o streams-solution-report ./streams_solution

clean:
	rm -f streams streams_solution *.qdrep *.sqlite
